### ISSUE TITLE
Layout issue with "Updating (game title)" dialog box

### ISSUE THREAD

**Issue by goblinpope** [somini/Pixelvision2#100]
![gvgzs2n 1](https://cloud.githubusercontent.com/assets/17583270/25160149/ed98fcfa-2479-11e7-9fa8-f033ba1d024a.png)
![7gsjhy5 1](https://cloud.githubusercontent.com/assets/17583270/25160223/5e752818-247a-11e7-8088-f6b16fabdeda.png)

Steam version: stable, date Mar 22 2017
Pixelvision2 version:  master branch, 641c75c

Looks like the "Launch whenever ready" option is causing the issue.

**Comment by mr-late** [comment]
Yeah that's a new option. I'll check it out when I can.

**Comment by mr-late** [comment]
This issue is now fixed on my fork. Download the master file from there.
