### ISSUE TITLE
Layout busted under new chat beta

### ISSUE THREAD

**Issue by flatluigi** [somini/Pixelvision2#105]

**Comment by Bluscream** [comment]
I got no problems, please describe!

![](https://i.imgur.com/3Dk1leZ.png)

**Comment by liznevada** [comment]
probably because you are not on the latest beta.
![image](https://user-images.githubusercontent.com/4228154/41323659-deacf6e8-6e7d-11e8-8828-f5244308ea51.png)

the details are here
https://steamcommunity.com/updates/chatupdate

**Comment by Bluscream** [comment]
I just got the latest beta and the friends window isn't even opening...

**Comment by NapoSky** [comment]
Same here, you must restart steam after going here : https://steamcommunity.com/updates/chatupdate#tryit

![image](https://user-images.githubusercontent.com/31205250/41366484-87a1e100-6f3c-11e8-8584-61d081c587cf.png)

**Comment by somini** [comment]
It seems Valve is migrating the chat to the web: https://steamcommunity.com/chat/

In that case, the skin will no longer control the UI.

**Comment by Bluscream** [comment]
Hmm so that means javascript/css would be required?

**Comment by somini** [comment]
Likely, but depending on the way it is done, it might be nigh-impossible to style.

If they use Web Components or one of those newfangled frameworks that uglify the CSS classes for performance (highly likely, but I haven't checked), it's game over.

**Comment by NapoSky** [comment]
Even the main UI can't be fixed ? I see Black4Blade try to do sth about this : https://github.com/Black4Blade/Pixelvision2/commit/45f403554005d6ed570613b6aa13144b55f5359e

**Comment by SzymonNadbrzezny** [comment]
@somini so you'll try to update pixelvision?

**Comment by Bluscream** [comment]
@NapoSky thanks for bringing that fork to my attention. Using that now :)

**Comment by NapoSky** [comment]
PR is passed : https://github.com/somini/Pixelvision2/pull/106
@mr-late should close this issue ;)

**Comment by mr-late** [comment]
Issue fixed, moving on.
