### ISSUE TITLE
No Steam Proton button

### ISSUE THREAD

**Issue by ipkpjersi** [somini/Pixelvision2#113]
As you can see in the top left corner of this picture, it says "runs" which means it runs using Steam Proton as I am on Linux, but there is no button for this:

![](https://i.imgur.com/pIgECpP.png)

**Comment by halbrd** [comment]
Would you be able to provide a screenshot of what it's supposed to look like (i.e. with the default Steam skin enabled) so we can understand what's not working properly?

**Comment by ipkpjersi** [comment]
Hi,

Sure, I can do that.

It should look like this for non-official Proton Compatible titles:

![](https://i.imgur.com/cTZV2rW.png)

It should look like this for official Proton Compatible titles:

![](https://i.imgur.com/j4y4TD4.png)

I hope this clears up any confusion.

Thanks.

**Comment by Black4Blade** [comment]
Hey I think I got it fixed
If you can test it and let me know, it's not perfect at all, will need a little more work, and will need to get in order something else that may be there but just want to know if this does fix the basic problem
https://github.com/Black4Blade/Pixelvision2/tree/BetaFastFix

@ipkpjersi

**Comment by ipkpjersi** [comment]
It's perfect for me, awesome! Nice job. Hopefully you can make a PR with these fixes and the PR gets merged.

**Comment by Black4Blade** [comment]
> It's perfect for me, awesome! Nice job. Hopefully, you can make a PR with these fixes and the PR gets merged.

I can manage, got access, not doing it yet, mostly because need to word some things there better :P
Besides that, it looks completely fine by you? by me it was squashed may have been because the VM was a low res

**Comment by ipkpjersi** [comment]
No resolution or stretching issues whatsoever. Looks perfect to me, but I can test it more later tonight.

edit: I tested it more, seems to be working perfectly fine for me even at various sizes etc.

**Comment by Black4Blade** [comment]
> No resolution or stretching issues whatsoever. Looks perfect to me, but I can test it more later tonight.
> 
> edit: I tested it more, seems to be working perfectly fine for me even at various sizes etc.

thanks for testing I put a pull request with the fix, just have to make sure its not breaking something else that or any other fix I put there before its merged

**Comment by Black4Blade** [comment]
Ok merged this should be fixed now
So closing this issue
