### ISSUE TITLE
[Question] Custom Download Speed per Menu

### ISSUE THREAD

**Issue by Bluscream** [somini/Pixelvision2#118]
I tried adding menu entries to switch between some custom throttles via menu (https://steamcommunity.com/groups/SteamClientBeta/discussions/1/350542145692693953/#c1637542668222388903) but none of these seem to work. Can anyone tell me why?

`<Steam Folder>\skins\mySkin\resource\menus\steam.menu`
```js
	Throttle {
		text = "Throttle"
		Infinite	{	text="Disable"	shellcmd="set_download_throttle -1" }
		StepZero	{	text="0 MB/s"		shellcmd="set_download_throttle 0" }
		StepOne		{	text="3.5 MB/s"	shellcmd="set_download_throttle 28000" }
	}

	Throttle2 {
		text = "Throttle 2"
		TInfinite	{	text="Disable"	command="DownloadThrottleKbps -1" }
		TStepZero {	text="0 MB/s"		command="DownloadThrottleKbps 0" }
		TStepOne	{	text="3.5 MB/s"	command="DownloadThrottleKbps 28000" }
	}
```

**Comment by Black4Blade** [comment]
I may be wrong, but I think it's likely it's locked on the backend, so we can't really add speeds by adding it like that
By the way sorry for the slow reply, seen this but wanted to see if I can find a way to test it, but sadly I do not

**Comment by Bluscream** [comment]
Weird, i wonder where the `shellcmd=` and `command=` thing differ

I thought `command=` is the same as if you would type it into the console. Thats why i thought `command="set_download_throttle X"` should work

**Comment by Black4Blade** [comment]
Closed this as now that Valve added the custom speed into the client this seems unneeded
If for some reason you want me to reopen it please let me know
