### ISSUE TITLE
Skin doesn't support new library beta

### ISSUE THREAD

**Issue by flatluigi** [somini/Pixelvision2#119]
I know the devs currently maintaining this are almost definitely aware of this already, but it's worth mentioning both for housekeeping and as a sign of there still being interest in seeing the project continue

**Comment by Black4Blade** [comment]
Thanks for opening, was planning to do it late, if no one else will get on this I am planning to do it next week when I hopefully will have time to get on it

**Comment by julliansl** [comment]
> I know the devs currently maintaining this are almost definitely aware of this already, but it's worth mentioning both for housekeeping and as a sign of there still being interest in seeing the project continue

I've put in a working solution for this, and it now has a pull request #120 , hopefully it gets merged in sometime.

**Comment by Black4Blade** [comment]
JSyLucero work was merged so this issue I think can be closed anyone has an issue with that?
