### ISSUE TITLE
Unsupported checkbox in settings menu:

### ISSUE THREAD

**Issue by flatluigi** [somini/Pixelvision2#124]
![image](https://puu.sh/EqgZL/2b24238618.png)

"Disable" box at top.

**Comment by julliansl** [comment]
I'll take a look into it. (Although I don't have that issue on my side...?)

**Comment by Black4Blade** [comment]
By the way was this issue fixed since then? can I close this?

**Comment by julliansl** [comment]
> By the way was this issue fixed since then? can I close this?

Yeah I think its actually fixed now, since I was never able to replicate the issue and its never shown up in testing.

**Comment by Black4Blade** [comment]
I think its this:
https://i.imgur.com/HBB4Wqf.png

And at least by me, it seems fixed, so going to close this, if it's found or if it's still happening to someone after updating the skin let me know, and will reopen
