### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ReyZ19** [somini/Pixelvision2#140]
![image](https://user-images.githubusercontent.com/77238876/116117823-5b921300-a6c5-11eb-8d35-0fa49419e176.png)

**Comment by Black4Blade** [comment]
Sorry I seem to be some what late to notice this :(
What language is that? @ReyZ19

**Comment by ReyZ19** [comment]
> Sorry I seem to be some what late to notice this :(
> What language is that? @ReyZ19

Turkish
