### ISSUE TITLE
Library and downloads are broken

### ISSUE THREAD

**Issue by reyaz006** [somini/Pixelvision2#141]
Since todays beta update. Can someone confirm?

**Comment by Black4Blade** [comment]
Both seem fine by me:
https://i.imgur.com/2TUzRBA.png
https://i.imgur.com/doZNWwH.png

**Comment by RetroMan77** [comment]
@reyaz006 Hi, Sorry for asking here. But i need your help with Onimusha 3 Pc Version. Kindly help me
