### ISSUE TITLE
New Downloads Page

### ISSUE THREAD

**Issue by mpql** [somini/Pixelvision2#142]
There's a new Downloads view that, as of yet, appears to be unstyled. No rush or obligation or anything, but figured I'd make an issue to track this. If I've got time around work I may try to work on it myself and submit a PR if I can.

Screenshot:

![image](https://user-images.githubusercontent.com/1709954/132848303-28725486-42eb-41c3-ba06-e0c57f633a85.png)

**Comment by Bluscream** [comment]
It's most likely HTML

**Comment by julliansl** [comment]
> It's most likely HTML

Yeah it's HTML styled with CSS. so there's not much we can do about it, because I believe to change it we need to modify the CSS provided by Steam's installation and then put it to read-only, I've tried it, its a little weird  and a bit annoying to work on due to that to be completely honest.

**Comment by mpql** [comment]
Closing this as no longer relevant per the new UI in #155.
