### ISSUE TITLE
Settings download new placement

### ISSUE THREAD

**Issue by Black4Blade** [somini/Pixelvision2#151]
It seems like there is something new in the Settings download, at least on Beta, that needs to be addressed
![image](https://user-images.githubusercontent.com/5269928/220493264-6b1d6bc3-a145-4cdb-8684-5e8456b847a7.png)

I will try to get to it tomorrow.

**Comment by Black4Blade** [comment]
Should we move the local download by region? or leave it down below?

![image](https://user-images.githubusercontent.com/5269928/220762128-55e1dcf4-0a99-4f8d-805c-fa4d84f76a95.png)

**Comment by halbrd** [comment]
Personally, I would consider the default skin the "canonical" layout and follow that

**Comment by Black4Blade** [comment]
> Personally, I would consider the default skin the "canonical" layout and follow that

Ya may be a good idea,
Will be also easy to do, seeing as its more or less just a copy paste of how its on Steam all ready :P
