### ISSUE TITLE
Font Issues on Linux

### ISSUE THREAD

**Issue by ghost** [somini/Pixelvision2#36]
Hey there. So apparently there's an issue for any Steam skin using a font other than the default provided by Steam. For more on the issue [check this thread on Pressure](https://github.com/DirtDiglett/Pressure-for-Steam/issues/116). So far the only solution so far appears to be using a different font on Linux (in this case, Arial, the default).

**Comment by zekesonxx** [comment]
This bug can be fixed by running Steam with [solus-project/linux-steam-integration](https://github.com/solus-project/linux-steam-integration).

So that way you can use nice fonts, and aren't stuck with using an awful font like Arial.

**Comment by somini** [comment]
@zekesonxx Thanks for that pointer, I wasn't aware of that project.

**Comment by NdranC** [comment]
@zekesonxx Do you mind describing how to achieve this fix? I installed LSI and I'm running steam native with LSI-steam but the font issues don't seem any different.

Just in case I do have Segoe WP installed correctly but steam seems to keep missalinging the menu icons at the top.

**Comment by zekesonxx** [comment]
This doesn't fix the misaligning text, that's an issue with Steam's UI toolkit.

**Comment by ghost** [comment]
Closing out old issue.
