### ISSUE TITLE
Warning/Error since pull41, missing panelBackground definition?

### ISSUE THREAD

**Issue by Mikachu** [somini/Pixelvision2#45]
Errors in resource/layout/downloadsummarypanel.layout:

```
Couldn't find color 'panelBackground' referenced in render fill comand 'fill( x0, y0, x0+50,    y1, panelBackground )'
Couldn't find color 'panelBackground' referenced in render fill comand 'gradient_horizontal( x0+50, y0, x0+100, y1, panelBackground,    panelBackgroundTransparent )'
Error parsing 'render' key in a style definition
```

I can't find any definition of panelBackground and panelBackgroundTransparent anywhere either.

**Comment by somini** [comment]
I took the liberty to edit your post to use 4 leading spaces for the error messages, that makes the error messages stand out in that box. You can also reference pull requests and issues in the body like this: #41 . That notifies whoever was involved in it, and makes a link.

As for the error you reported, it's absolutely correct, it seems that a couple of lines were missing, the default skin has them. I'll add them and test it right away.

**Comment by somini** [comment]
Well, since that code block had an error, it sets no colors at all, so I just used `none` for both colors.
I'd appreciate if you can test it.
@CaptainMagma can chime in later, in the default skin there's a blue gradient.

**Comment by Mikachu** [comment]
That seems to have done the trick.
(I didn't know the pull request numbers were == issue numbers, and forgot about the other formatting stuff, thanks).
