### ISSUE TITLE
Music Player time slider

### ISSUE THREAD

**Issue by somini** [somini/Pixelvision2#46]
![bug](https://i.imgur.com/e2qfxsA.png)
As reported in the forums: http://steamcommunity.com/groups/pixelvision2/discussions/0/527274088399561028/

I think I read in the Steam beta news that this was introduced as a new feature, should be a case of copying the default skin block.

**Comment by CaptainMagma** [comment]
Yeah, I'll have the fix out probably within the next 15 minutes.

**Comment by somini** [comment]
Thanks for the fast response. :+1:
