### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Efreak** [somini/Pixelvision2#49]
Probably nobody else is going to notice this much, but it is there.
1. When you open the dialog to select a folder for screenshots, [things look ok](http://i.imgur.com/CuwZwDS.png):
   - The + to the left of unopened folders with subfolders doesn't show up
   - The font is big as it should be, and you can read it
2. When you scroll up, [this changes](http://i.imgur.com/H0bpfuz.png):
   - The + to the left of unopened folders with subfolders is still missing
   - The font is small on some of the folders
3. After you hover over some of the subfolders, [it changes more](http://i.imgur.com/H7QBW1h.png):
   - The + is still not there.
     - However, after you double-click a folder to show subfolders, the -/+ for it shows up (as do those for its subfolders), which leads me to believe this is a bug with steam, not the skin
   - The font gets bigger, but it's cut off at the bottom now
     - The folder names are now right-aligned to somewhere in the middle, and cut off at the end. I'm guessing this is also a steam bug?

Screenshots:

[1. ![](http://i.imgur.com/CuwZwDSs.png)](http://i.imgur.com/CuwZwDS.png) . . [2. ![](http://i.imgur.com/H0bpfuzs.png)](http://i.imgur.com/H0bpfuz.png) . . [3. ![](http://i.imgur.com/H7QBW1hs.png)](http://i.imgur.com/H7QBW1h.png)

Notes:
1. I'm using the (+3) font sizes tweak, so that might be related?
2. I tried debugging with VGUI, but hitting f6 (or alt-tabbing) has the same effect as hovering (see next)
3. The same issue occurs with the Select Music Library dialog.

**Comment by somini** [comment]
Sorry for taking so long to answer this, I was away for this past few days.

Points 1 and 2 are not a bug, the + doesn't show up because you only see the child folders, not the parent ones.
And for those font changes, I managed to reproduce it. Do you know where in what file the fonts for that screen are defined? I think there's a "hover" missing somewhere.

**Comment by somini** [comment]
I tested this issue with the Pressure for Steam skin and it's the exact same problem, so I'm positive this is a Steam client issue. How's the process for reporting this kind of bugs?

**Comment by Efreak** [comment]
I have no clue. It's also not a huge deal, I doubt anyone uses this window more than once or twice.

**Comment by ghost** [comment]
This is done by design, actually (has been a thing for over FIVE years.)
