### ISSUE TITLE
UI display issue

### ISSUE THREAD

**Issue by n0f4c3** [somini/Pixelvision2#52]
![ashampoo_snap_2015 10 05_17h27m30s_002_](https://cloud.githubusercontent.com/assets/14986315/10294170/a2beb574-6b86-11e5-838e-5ec21513ab41.png)

**Comment by BlackHazel** [comment]
Works fine if you use the Beta.

View > Settings > Account > Beta Participation > Change > Steam Beta Update > OK > OK > Restart Steam.

![beta2](https://cloud.githubusercontent.com/assets/12218001/10305432/5bd237b8-6c20-11e5-8ce2-88b478d5e1e6.jpg)

**Comment by somini** [comment]
What @BlackHazel said, thanks for the quick response.
