### ISSUE TITLE
UI glitch after the recent Steam update

### ISSUE THREAD

**Issue by Starfox64** [somini/Pixelvision2#53]
Since today's update there is a glitch in the top left corner of the window.
![](http://i.imgur.com/F9kOMzv.png)

**Comment by joedf** [comment]
Try downloading from master not from releases.
I had that, seems fixed. It's actually about connecting a phone to your account.

**Comment by Starfox64** [comment]
That fixed it, since the master was 14 days old I thought it came from the update.

**Comment by joedf** [comment]
Great! :+1:
