### ISSUE TITLE
Chinese interface display error.

### ISSUE THREAD

**Issue by Sonic853** [somini/Pixelvision2#59]
Please fix.
![Chinese interface display error](https://php-853.rhcloud.com/201601060242450.png)

**Comment by somini** [comment]
Did you change the locale?
It's here:
https://github.com/somini/Pixelvision2/blob/master/locale.ini#L29-L37
Just uncomment the correct line for your language.

**Comment by Sonic853** [comment]
Thank you for your answer! My problem has been solved.

**Comment by somini** [comment]
Glad to be if assistance.
