### ISSUE TITLE
Library, Community icons are so static so they don't move with buttons (custom languages)

### ISSUE THREAD

**Issue by avsaponchik** [somini/Pixelvision2#67]
![default](https://cloud.githubusercontent.com/assets/1337953/13291820/5655491e-db2a-11e5-8889-8c118a21234d.PNG)
![2](https://cloud.githubusercontent.com/assets/1337953/13291821/565734cc-db2a-11e5-8dac-bb07dfb99445.PNG)

Sorry for my russian.

**Comment by somini** [comment]
Did you change the locale.ini file? There's instructions in the comments there.
If you need help, answer here, I'm on mobile and can't give you details instructions

**Comment by avsaponchik** [comment]
got it, thanks!

**Comment by somini** [comment]
Glad it was solved.
