### ISSUE TITLE
Download link on lower right corner

### ISSUE THREAD

**Issue by somini** [somini/Pixelvision2#70]
Investigate if this is possible:
http://steamcommunity.com/groups/pixelvision2/discussions/0/371918937259047237/

**Comment by flatluigi** [comment]
It's actually the lower right corner, where the "X of X items complete" text ends up when there's finished, uncleared downloads.

**Comment by somini** [comment]
Thanks for the correction, fixed.

**Comment by Black4Blade** [comment]
Well seems this happen at some point, so going to close this topic now :)
