### ISSUE TITLE
New VR Teather checkbox broken.

### ISSUE THREAD

**Issue by JukePlz** [somini/Pixelvision2#71]
VR checkbox in options (in-game settings) is unaligned and broken (can't be clicked)

This is what it looks by default on the steam skin:
![default](http://i.imgur.com/PImo7AU.png)

And it's broken like this on PixelVision2:
![pixelvision](http://i.imgur.com/VtkCd7c.png)

**Comment by somini** [comment]
This is not really closed, I'm pretty sure I fixed this, but I haven't tested on Windows and on Linux and Mac those checkboxes don't appear. Can you confirm this bug is fixed?

**Comment by somini** [comment]
Oh, and many thanks for a detailed bug report, appreciated it.

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/14370542/d085f9a2-fd37-11e5-86b7-1c70f8cf8790.PNG)

**Comment by bykidi** [comment]
I think these checkboxes should be moved a bit higher or other stuff should be moved lower. Its just look wierd.

**Comment by avsaponchik** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/14370598/575ddf4e-fd38-11e5-9b1a-624003d23d2b.PNG)

**Comment by avsaponchik** [comment]
Its my red line btw. I think this checkboxes should be aligned with other stuff and also moved a bit higher or other stuff moved a bit lower

**Comment by clevelandj** [comment]
Agreed. I tried to tidy up this panel in https://github.com/somini/Pixelvision2/pull/72/. I didn't realign the checkboxes, but I modified the margins to make things fit better.

For reference:
![image](https://cloud.githubusercontent.com/assets/10454355/14371407/57182c3e-fd05-11e5-8c53-1f5ca66071d1.png)

**Comment by somini** [comment]
I just pushed @clevelandj 's PR and aligned the checkboxes. Thanks everyone!
Please reopen if there's any problems.
