### ISSUE TITLE
(DEU) Screenshot manager button overlaps "flag as spoiler" option when window is at smallest width

### ISSUE THREAD

**Issue by EvilJackCarver** [somini/Pixelvision2#76]
When the client is in German and the German localisation alteration is selected, when the Screenshot Manager window is set to the minimum width, the "Flag as Spoiler" option ("Als Spoiler markieren") is overlapped by the button to go to the online gallery.

![](http://i.imgur.com/7R3KHgz.png)

According to the F6 menu, the "Go to Online Gallery" key is in `resource/layout/screenshotmanager.layout`, in the `CScreenshotManager / CScreenshotManager` container, the selection being `view_screenshots / Button`.

The "flag as spoiler" option is in the same file, same container, but the selection shows `spoiler_checkbox / CheckButton`.

Screenshots of the F6 menu: [Gallery button](http://i.imgur.com/7zkLQNq.png), and [Spoiler button](http://i.imgur.com/SQPw55r.png)

This issue does not reproduce itself using the standard Steam skin, because the Spoiler checkbox is on a different "line" than the buttons:

![](http://i.imgur.com/raQ7tvt.png)

---

PixelVision² build dated 2016-02-12, Steam client build dated 2016-06-14 16:27:18 (timezone not specified). Windows 7, Build 7601 x64. I am using the Steam Piston and Smaller Big Picture Icon overrides.

The following items in my settings.ini are uncommented:
- Alternative Font
- Tweak: Game Title Background (Library, Details view)
- Tweak: Replace Big Picture Mode Icon (Use Controller Icon)

I have German uncommented in my locale.ini.

**_Note: This issue may affect other languages, not just German.**_

Minor issue - trivial at best - but I figured I'd report it anyway. This issue can be worked around by resizing the window, or clicking the "Als Spoiler markieren" text.

**Comment by mr-late** [comment]
Thanks for the thorough info. I'll see to this bug and find the best way to fix it.

**Comment by somini** [comment]
I want to second this very complete bug report. The layout it's geared towards the english word metrics, perhaps it's for the best to split the commands into two different lines.

**Comment by mr-late** [comment]
Yeah and I'm afraid Pixelvision just might always be geared towards English speakers since they are the biggest demographic (46.62% of all steam users). That doesn't mean we shouldn't fix bugs like these that don't affect the English version, it's just going to take longer.

**Comment by mr-late** [comment]
Fix is done now in #77

**Comment by somini** [comment]
After some back-and-forth to test this, Mr. Late solved this issue, I pushed it to a new branch, `pull/77`.
@EvilJackCarver could you please test this and see if the issue remains? I'll push this to the master branch in a couple of days, since on our end it looks good.
Here's the direct link to the version: https://github.com/somini/Pixelvision2/archive/pull/77.zip

**Comment by EvilJackCarver** [comment]
Can confirm fixed.

![](http://i.imgur.com/UH6Weo6.png)

Gonna go ahead and close this then. Cheers!

**Comment by somini** [comment]
Thanks! I'll merge the changes to master then.
