### ISSUE TITLE
Added new button to Downloads Settings page

### ISSUE THREAD

**Issue by avsaponchik** [somini/Pixelvision2#80]
11 August - Steam Client Beta Update

Added button to clear local cache under download settings. This may fix downloads by removing stale or corrupt cached data.

![default](https://cloud.githubusercontent.com/assets/1337953/17575085/fcf7d494-5f6e-11e6-83c5-d1a19e1cd449.PNG)

**Comment by avsaponchik** [comment]
#82

**Comment by somini** [comment]
Should be fixed in #82, so I'm closing this.
