### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by BKPepe** [somini/Pixelvision2#9]
I must download Pixelvision(v1) for Fonts, please upload them here.

**Comment by somini** [comment]
I'm not sure how legal is to redistribute the fonts, but the original releases had them, the Fonts folder:
https://www.dropbox.com/s/vsz71n7f176pdom/PixelVision_2015-0101_Final.zip

**Comment by BKPepe** [comment]
Hello,
I don't know it either.
Maybe just put links for fonts in readme?

**Comment by somini** [comment]
Yeah, I've been meaning to write a proper Readme to explain how to install it and keep it updated, but it's still on my TODO list.
