### ISSUE TITLE
Latest steam beta update

### ISSUE THREAD

**Issue by mr-late** [somini/Pixelvision2#94]
Latest steam beta update removed options for Video Driver updates.

**Comment by mr-late** [comment]
PR #95 uploaded a fix.  Also includes a change to the about_version.tga file. It was last updated on 29th of June last year.

**Comment by mr-late** [comment]
On an unrelated note, I noticed the "Help -> About steam" graphics date back to 29th of June 2016. I would suggest removing the lowest line that shows the date for the Skin.

**Comment by somini** [comment]
Thanks for the PR, merged.
