### ISSUE TITLE
Some things in Settings > Downloads is misplaced

### ISSUE THREAD

**Issue by MetroidCatcher** [somini/Pixelvision2#98]
What Title is saying.
Original: ![steam_2017-03-23_22-37-10](https://cloud.githubusercontent.com/assets/16920375/24271374/d8c40bee-1010-11e7-97eb-9ae0e489b8d9.jpg)
Pixelvision2: ![steam_2017-03-23_22-36-43](https://cloud.githubusercontent.com/assets/16920375/24271379/db6989d2-1010-11e7-9830-11d1ef53416f.jpg)

**Comment by mr-late** [comment]
I just checked both stable and beta version of steam and everything is working fine.  Try reinstalling the skin.

**Comment by MetroidCatcher** [comment]
Looks like, i had an older version or something. Well, fixed now for me :D
